// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWA8m4CXzByQVBs38dRGoDfKio1-laC4',
    appId: '1:493769135029:web:8f5cee0962f46dda417ffc',
    messagingSenderId: '493769135029',
    projectId: 'notaya-2d760',
    authDomain: 'notaya-2d760.firebaseapp.com',
    storageBucket: 'notaya-2d760.firebasestorage.app',
    measurementId: 'G-6Y5BCTKGL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5o25evMgYwYh2t30TtRaJJ5mbJfMG4Uw',
    appId: '1:493769135029:android:8d3491140c8b5544417ffc',
    messagingSenderId: '493769135029',
    projectId: 'notaya-2d760',
    storageBucket: 'notaya-2d760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp5EcZEabDEFYmotrXn4Y1Unjm3dlg-nE',
    appId: '1:493769135029:ios:4470fed8fe1592a8417ffc',
    messagingSenderId: '493769135029',
    projectId: 'notaya-2d760',
    storageBucket: 'notaya-2d760.firebasestorage.app',
    iosBundleId: 'com.example.notesLocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp5EcZEabDEFYmotrXn4Y1Unjm3dlg-nE',
    appId: '1:493769135029:ios:4470fed8fe1592a8417ffc',
    messagingSenderId: '493769135029',
    projectId: 'notaya-2d760',
    storageBucket: 'notaya-2d760.firebasestorage.app',
    iosBundleId: 'com.example.notesLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXWA8m4CXzByQVBs38dRGoDfKio1-laC4',
    appId: '1:493769135029:web:6fb319782cba13b5417ffc',
    messagingSenderId: '493769135029',
    projectId: 'notaya-2d760',
    authDomain: 'notaya-2d760.firebaseapp.com',
    storageBucket: 'notaya-2d760.firebasestorage.app',
    measurementId: 'G-2RCS21L4WF',
  );
}